
version: '3.8'
services:
  dev-database:
    container_name: dev-database
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:   
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc
      POSTGRES_DB: qldt
    networks:
      - nestjs-networks

networks:
  nestjs-networks:

# docker compose up -d